codecov:
  branch: master
comment:
  behavior: default
  require_changes: true
coverage:
  round: down
  precision: 2
  status:
    changes: false
    project:
      default:
        target: 22.0
        threshold: 0.1
    patch:
      default:
        branches: null
fixes:
  - "/opt/::"
