---
name: isotovideo
# yamllint disable-line rule:truthy
on: [push, pull_request]
jobs:
  schedule:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    container:
      image: "registry.opensuse.org/devel/openqa/containers/isotovideo:qemu-x86"
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      - name: Verify the test schedule including wheels
        run: ./test
        env:
          WITH_COVER_OPTIONS: 1
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f  # v7.0.0
        with:
          # should not be necessary for public repos, but might help avoid sporadic upload token errors
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./cover_db/codecov.json
          fail_ci_if_error: true
          verbose: true
